/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package disease_analyzer;

import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class hospital_registration extends javax.swing.JFrame {

    /**
     * Creates new form hospital_registration
     */
    public hospital_registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jfname = new javax.swing.JTextField();
        jlname = new javax.swing.JTextField();
        juname = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jage = new javax.swing.JTextField();
        jccode = new javax.swing.JComboBox<>();
        jphone = new javax.swing.JTextField();
        jpass = new javax.swing.JPasswordField();
        jcity = new javax.swing.JTextField();
        jpcode = new javax.swing.JTextField();
        jpaddress = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jselector = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        juserid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectImage/medical (2).png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("MV Boli", 1, 67)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("M");

        jLabel15.setFont(new java.awt.Font("MV Boli", 1, 67)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("C");

        jLabel16.setFont(new java.awt.Font("MV Boli", 1, 67)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("D");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Feel Free To Discuss About Your Disease");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(134, 134, 134))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(jLabel17)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("REGISTRATION FORM");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 66, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("First Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 192, -1, 26));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Last Name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 224, -1, 26));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("User Name:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 256, -1, 26));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Email:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 288, -1, 26));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Password:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 320, -1, 26));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Age:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 352, -1, 26));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Phone No:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 384, -1, 26));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("City:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 416, -1, 26));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Postal Code:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 448, -1, 26));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Present Address:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 480, -1, 26));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 153, -1, 397));

        jfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfnameActionPerformed(evt);
            }
        });
        jPanel2.add(jfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 197, 186, -1));
        jPanel2.add(jlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 228, 186, -1));
        jPanel2.add(juname, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 259, 186, -1));
        jPanel2.add(jemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 292, 186, -1));
        jPanel2.add(jage, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 354, 71, -1));

        jccode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "93", "355", "213", "1684", "376", "244", "1264", "672", "1268", "88", "54", "374", "297", "61", "43", "994", "1242", "973", "880", "1246", "375", "32", "501", "229", "1441", "975", "387", "267", "55", "246", "1284", "673" }));
        jPanel2.add(jccode, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 385, -1, -1));
        jPanel2.add(jphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(844, 385, 127, -1));
        jPanel2.add(jpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 323, 186, -1));
        jPanel2.add(jcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 423, 71, -1));
        jPanel2.add(jpcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 454, 71, -1));
        jPanel2.add(jpaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 480, 186, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 583, 111, 36));

        jselector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User", "Doctor" }));
        jPanel2.add(jselector, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 529, 186, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Register As:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 524, -1, 26));

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel18.setText("Click Here to Login");
        jLabel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.white, null, null));
        jLabel18.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel18MouseDragged(evt);
            }
        });
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel18MousePressed(evt);
            }
        });
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 637, 124, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("User Id:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 160, -1, 26));

        juserid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juseridActionPerformed(evt);
            }
        });
        jPanel2.add(juserid, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 166, 186, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1109, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String userid =  juserid.getText(); //getting user id
        String fname = jfname.getText(); //getting first name
        String lname = jlname.getText(); //getting last name
        String uname = juname.getText(); //getting user name
        String email = jemail.getText(); //getting email
        String password = String.valueOf(jpass.getPassword()); //getting password
        String age =  jage.getText(); //getting age
        String countrycode = jccode.getSelectedItem().toString(); //getting country code for phone numebr
        String phone = jphone.getText(); //getting phone number
        String city = jcity.getText(); //getting city name
        String postcode = jpcode.getText(); //getting post code
        String presentaddress = jpaddress.getText(); //getting present address
        String f_phone = countrycode + phone; //concating country code and phone number
        String address = city +","+presentaddress + "," + postcode; //concating address
        String Query = null; //declaring for making query
        String selector = jselector.getSelectedItem().toString(); //getting selected item to defferentiat the query
        if(userid.equals("")){
            JOptionPane.showMessageDialog(null, "Enter your User id first");
        }
        else if(fname.equals("")){ //check first name field is empty or not
            JOptionPane.showMessageDialog(null, "Enter your First name");
        }
        else if(lname.equals("")){ //check last name field is empty or not
            JOptionPane.showMessageDialog(null, "Enter your last name");
        }
        else if(uname.equals("")){ //check user name field is empty or not
            JOptionPane.showMessageDialog(null, "Enter your user name");
        }
        else if(email.equals("")){ //check email's validity and check field is emply or not
            JOptionPane.showMessageDialog(null, "Enter your email");
        }
        else if(age.equals("")){ //check age validity and check field is empty or not
            JOptionPane.showMessageDialog(null, "Enter your age");
        }
        else if(city.equals("")){
            JOptionPane.showMessageDialog(null, "Enter your city name");
        }
        else if(phone.equals("")){ //check phone validity and check field is empty or not
            JOptionPane.showMessageDialog(null, "Enter your phone number");
        }
        else if(presentaddress.equals("")){
            JOptionPane.showMessageDialog(null, "Enter your Present Address");
        }
        else{
            PreparedStatement ps;
            if("Admin".equals(selector)){
                if(id_validation(userid) == false){
                    JOptionPane.showMessageDialog(null, "User id formation is not right");
                }
                else if(email_validation(email) == false){
                    JOptionPane.showMessageDialog(null, "Email formation is not right");
                }
                else if(age_validation(age) == false){
                    JOptionPane.showMessageDialog(null, "Age Formation is not right");
                }
                else if(phone_validation(f_phone) == false){
                    JOptionPane.showMessageDialog(null, "Phone number formation is not right");
                }
                else{
                    Query = "Insert into admin(admin_id,first_name,last_name,user_name,email,password,age,address,phone) values(?,?,?,?,?,?,?,?,?)";
                }
            }
            else if("User".equals(selector)){
                if(email_validation(email) == false){
                    JOptionPane.showMessageDialog(null, "Email formation is not right");
                }
                else if(age_validation(age) == false){
                    JOptionPane.showMessageDialog(null, "Age Formation is not right");
                }
                else if(phone_validation(f_phone) == false){
                    JOptionPane.showMessageDialog(null, "Phone number formation is not right");
                }
                else{
                    Query = "Insert into user(user_id,first_name,last_name,user_name,email,password,age,address,phone) values(?,?,?,?,?,?,?,?,?)";
                }
            }
            else if("Doctor".equals(selector)){
                if(email_validation(email) == false){
                    JOptionPane.showMessageDialog(null, "Email formation is not right");
                }
                else if(age_validation(age) == false){
                    JOptionPane.showMessageDialog(null, "Age Formation is not right");
                }
                else if(phone_validation(f_phone) == false){
                    JOptionPane.showMessageDialog(null, "Phone number formation is not right");
                }
                else{
                    Query = "Insert into doctor(doctor_id,first_name,last_name,user_name,email,password,age,address,phone) values(?,?,?,?,?,?,?,?,?)";
                }
            }
            try{
                ps = myconnection.getConnection().prepareCall(Query);
                
                ps.setString(1, userid);
                ps.setString(2, fname);
                ps.setString(3, lname);
                ps.setString(4, uname);
                ps.setString(5, email);
                ps.setString(6, password);
                ps.setString(7, age);
                ps.setString(8, address);
                ps.setString(9, f_phone);
                if(ps.executeUpdate() > 0){
                    JOptionPane.showMessageDialog(null, "New "+selector+" Information Added");
                }
                
            }catch(HeadlessException | SQLException ex){
                Logger.getLogger(hospital_registration.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel18MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseDragged
        hospital_login hreg = new hospital_login();
        hreg.setVisible(true);
        hreg.pack();
        hreg.setLocationRelativeTo(null);
        hreg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseDragged

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        hospital_login hreg = new hospital_login();
        hreg.setVisible(true);
        hreg.pack();
        hreg.setLocationRelativeTo(null);
        hreg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MousePressed
        hospital_login hreg = new hospital_login();
        hreg.setVisible(true);
        hreg.pack();
        hreg.setLocationRelativeTo(null);
        hreg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel18MousePressed

    private void juseridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juseridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juseridActionPerformed
    public static boolean email_validation(String email){
        String emailregex = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                            "[a-zA-Z0-9_+&*-]+)*@" + 
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
                            "A-Z]{2,7}$";
        Pattern pat1 = Pattern.compile(emailregex);
        if(email == null){
            return false;
        }
        else
            return pat1.matcher(email).matches();
    }
    public static boolean age_validation(String age){
        String ageregex = "^\\d+$";
        
        Pattern pat2 = Pattern.compile(ageregex);
        if(age == null)
            return false;
        return pat2.matcher(age).matches();
        
    }
    public static boolean phone_validation(String f_phone){
        String phoneregex = "^\\d+$";
        
        Pattern pat3 = Pattern.compile(phoneregex);
        if(f_phone == null){
            return false;
        }
        return pat3.matcher(f_phone).matches();
    }
    public static boolean id_validation(String userid){
        String idregex = "^\\d+$";
        
        Pattern pat4 = Pattern.compile(userid);
        if(userid == null){
            return false;
        }
        return pat4.matcher(userid).matches();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hospital_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hospital_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hospital_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hospital_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hospital_registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jage;
    private javax.swing.JComboBox<String> jccode;
    private javax.swing.JTextField jcity;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jfname;
    private javax.swing.JTextField jlname;
    private javax.swing.JTextField jpaddress;
    private javax.swing.JPasswordField jpass;
    private javax.swing.JTextField jpcode;
    private javax.swing.JTextField jphone;
    private javax.swing.JComboBox<String> jselector;
    private javax.swing.JTextField juname;
    private javax.swing.JTextField juserid;
    // End of variables declaration//GEN-END:variables
}
